In [17]:
import numpy as np

In [24]:
def conv2d(input_matrix, kernal, stride=1, padding=0):

    if padding > 0:
        input_pad = np.pad(input_matrix, ((padding,padding),(padding,padding)), mode='constant')
    else:
        input_pad = input_matrix
    
    input_height, input_width = input_pad.shape
    kernal_height, kernal_width = kernal.shape

    output_height = (input_height - kernal_height)//stride + 1
    output_width = (input_width - kernal_width)//stride + 1

    output_matrix = np.zeros((output_height, output_width))

    for i in range(0, output_height):
        for j in range(0, output_width):
            region = input_pad[i*stride:i*stride + kernal_height, j*stride:j*stride + kernal_width]
            output_matrix[i, j] = np.sum(region*kernal)
    return output_matrix

In [28]:
input_matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
kernal = np.array([[1, 0], [0, -1]])

In [30]:
output = conv2d(input_matrix, kernal, stride=1, padding=1)
print(output)

[[ -1.  -2.  -3.  -4.   0.]
 [ -5.  -5.  -5.  -5.   4.]
 [ -9.  -5.  -5.  -5.   8.]
 [-13.  -5.  -5.  -5.  12.]
 [  0.  13.  14.  15.  16.]]
